### PR TITLE
Image conversion fixes

### LINKED ISSUE #490: Fix mobile image conversion in docker container
The current banners branch contains an image to mobile image conversion that works fine locally but still throws a file not found exception when run in a docker container.
It either is a problem with the third party library scrimage rights to write files within the docker container or plain path problems.

### PR DESCRIPTION
**Pull request by mpsonntag**
This PR
- fixes #490; It seems that the third party dependency for image conversion resolves paths differently than the native libraries. This lead to the case that compressed images could not be saved when the project was run inside a docker container.
- `Future` is now used to do the image compression for banners and figures to make sure the frontend does not have to wait until an image compression is done. Since the compression takes quite some time, it would block a user when uploading a banner or an abstract figure until the compression was done.
- Updates the changelog with the latest changes for release v1.3.
- Renames all usages of the paths `banner` and `banner_mobile` to the respective plural forms `banners` and `banners_mobile` to use the same convention as for `figures`.
- The class `FiguresMobileService` had only a single method that was used. This method was moved to the `FigureService` class, the usage was adjusted accordingly and the `FiguresMobileService` class was removed.
- The test setup now properly removes mobile figures, banners and mobile banners that are created during the test runs.
- Tests for mobile figures and banners were added.

### CODE REVIEW

File: app/service/FigureService.scala [hunk 1]
```diff
@@ -113,16 +115,35 @@ class FigureService(figPath: String, figMobilePath: String) {
...
+      // the docker environment.
+      var figure_file = new File(figPath, fig.uuid)
+      var mobile_file = new File(figMobilePath, fig.uuid)
+
+      try {
+        var mobile_image = Image.fromFile(figure_file)
+      } catch {
+        case nofile: NoSuchFileException => {
+          val figure_path = Paths.get("/srv", "gca", figPath, fig.uuid).normalize.toString
+          val mobile_path = Paths.get("/srv", "gca", figMobilePath, fig.uuid).normalize.toString
```
Comment (achilleas-k) [inline app/service/FigureService.scala]: Would a more general solution be always convert paths to abs paths everywhere (or maybe directly from the settings)?  Is there a reason that wouldn't work?

**Comment by achilleas-k** [comment]
Question/comment converted to issue to be addressed separately.  Merging now.
